### ISSUE TITLE
Safari private browser

### ISSUE THREAD

**Issue by RoelandSalij** [mendix/LoginForm#11]
See here:
https://mxforum.mendix.com/questions/8913/Login-form-widget--Safari-private-browsing-mode

**Comment by edwinmp** [comment]
Appears to be a problem in the Mendix core occurring on Safari running incognito. Browser shows the default Mendix login page instead of whatever page the user set. All attempts to login return u to that login page.

Will log a ticket for it.

**Comment by rickyv3** [comment]
Confirmed this is an issue as well and reported to Mx. Occurs when utilizing Safari browser in incognito mode - issue is immediately resolved when incognito is turned off and browser refreshed.

**Comment by JelteMX** [comment]
Related to support ticket 466665, will analyse and see if it can be fixed

**Comment by JelteMX** [comment]
This is tested in 6.10.0 and is no longer an issue. Related I added a fix in 3.5.1
