### ISSUE TITLE
Cannot add labels 

### ISSUE THREAD

**Issue by siddiqui111** [mendix/LoginForm#13]
Hi,

I had a requirement on one of the project to add labels to username and password inputs but this options is currently not available in the widget so I had to edit the widget and change the HTML to add labels. There is an option to add placeholder text, but nothing for adding labels. It will be nice to have an option to show or hide labels (Show label: Yes/No option) and if yes then a field to populate so that we can enter the label name (both for username and password). 

Thanks
Mohammed Siddiqui
![image](https://cloud.githubusercontent.com/assets/17008125/15609468/1d5012ac-2418-11e6-9253-1e9588358e1c.png)

Mohammed Siddiquiohammed Siddiqui

**Comment by JelteMX** [comment]
Fixed in [3.5.0](https://github.com/mendix/LoginForm/releases/tag/v3.5.0)
