### ISSUE TITLE
Ticket 466011 - Widget 'LoginForm' option to present email specific keyboard

### ISSUE THREAD

**Issue by JelteMX** [mendix/LoginForm#14]
Feature request: We use email addresses as user ID's, so would it be possible for the LoginForm widget to have an option to trigger the email specific keyboard on tablets/phones so that common characters user in emails (e.g. '@' or '_' ) are readily available to the user.

**Comment by rickyv3** [comment]
Feature request - notify the user if / when they have failed to login 3 times, and thus their account is locked for 5 minutes (per Mendix's standard settings).

**Comment by JelteMX** [comment]
Fixed in [3.5.0](https://github.com/mendix/LoginForm/releases/tag/v3.5.0)
