### ISSUE TITLE
Feature Request - Notify user when / if they have failed to login using the proper credentials after 3 failed attempts and thus account is locked for 5 minutes.

### ISSUE THREAD

**Issue by rickyv3** [mendix/LoginForm#15]
Feature Request - Notify user when / if they have failed to login using the proper credentials after 3 failed attempts and thus account is locked for 5 minutes.

**Comment by edwinmp** [comment]
Hi,

Will be taking on this request but need your opinions on the better of three implementations:

1. The Mendix core returns information on the whether a user account is blocked and then display this feedback to the user. Currently, Mendix doesn't support this and claims incorrect credentials even in this event. It'd be great if Mendix at least provides an option in the Project Security settings that lets a developer chose whether to return blocked status or not.

In the absence of the above:
2. Keep track of entered usernames and after the second failed attempt on each username, warn the user that their account by that username shall be blocked for 5 minutes should login with that username fail a third time.
3. Only keep track of the failed attempts and after the second failure, notify the user in a generic feedback message that entering the wrong credentials thrice for a particular username shall block the respective account for 5 minutes.

Note: Either implementation can be disabled within the widget settings.

**PROS**
2. - Notifies based on number of failures per usernames

3. - Non-repetitive i.e Only shows the necessary feedback once.

Suggestions for other alternatives are welcome as well as an insight into how Mendix would prefer to have this feature implemented.

**Comment by rickyv3** [comment]
My vote is for #2.

Best,

Ricky Volz
kinetech <http://kinetechcloud.com> *| *tel: 210.254.4988

**Comment by JelteMX** [comment]
Fixed in [3.5.0](https://github.com/mendix/LoginForm/releases/tag/v3.5.0)
